// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRRUV2FSVUjm7u9D2p3LwY9VE6GFMs4UY',
    appId: '1:932825360848:web:7e03b09eb77a56267831d5',
    messagingSenderId: '932825360848',
    projectId: 'todo-hti-9fdd2',
    authDomain: 'todo-hti-9fdd2.firebaseapp.com',
    storageBucket: 'todo-hti-9fdd2.appspot.com',
    measurementId: 'G-STCMZ2JWR6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfaHTH1BGXmINr4X8sLpWJ_YHVR8Zy2SU',
    appId: '1:932825360848:android:72d6b3e771ac7e6c7831d5',
    messagingSenderId: '932825360848',
    projectId: 'todo-hti-9fdd2',
    storageBucket: 'todo-hti-9fdd2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoV8Ly-v7mKbZ2mISVjbrnVG2RdHWCrI4',
    appId: '1:932825360848:ios:3963abc1bd172f6e7831d5',
    messagingSenderId: '932825360848',
    projectId: 'todo-hti-9fdd2',
    storageBucket: 'todo-hti-9fdd2.appspot.com',
    iosClientId: '932825360848-9tj5rd13unfs6mtnfadd5g4893u6lorp.apps.googleusercontent.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoV8Ly-v7mKbZ2mISVjbrnVG2RdHWCrI4',
    appId: '1:932825360848:ios:3963abc1bd172f6e7831d5',
    messagingSenderId: '932825360848',
    projectId: 'todo-hti-9fdd2',
    storageBucket: 'todo-hti-9fdd2.appspot.com',
    iosClientId: '932825360848-9tj5rd13unfs6mtnfadd5g4893u6lorp.apps.googleusercontent.com',
    iosBundleId: 'com.example.todo',
  );
}
